In [0]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

In [0]:
close_prices = pd.read_csv('close_prices.csv')

In [0]:
x = close_prices.drop(['date'], axis=1)

In [13]:
pca = PCA(n_components=10)
pca.fit(x)
pca.explained_variance_ratio_

array([0.73897118, 0.11007169, 0.04995088, 0.0287492 , 0.02215448,
       0.01931577, 0.00674853, 0.00614091, 0.00320594, 0.00305611])

In [0]:
df = pd.DataFrame(pca.transform(x))
y = df[0]

In [0]:
dj = pd.read_csv('djia_index.csv')
y_test = dj['^DJI']

In [25]:
corr = np.corrcoef(y, y_test)
corr

array([[1.        , 0.90965222],
       [0.90965222, 1.        ]])

In [26]:
pca.explained_variance_

array([1522.30984761,  226.75203269,  102.90079304,   59.22448474,
         45.63910225,   39.79124256,   13.90224179,   12.65051773,
          6.6043666 ,    6.29570803])

In [45]:
comp_0 = pd.Series(pca.components_[0])
comp_0_top = comp_0.sort_values(ascending=False).head(1).index[0]
x.columns[comp_0_top]

'V'