# Нейронные сети. Основы

## Реализация перцептрона

Перцептрон - это модель, предложенная Френком Розенблаттом в 1957 году и являющаяся прообразом современных нейронных сетей. По своей сути она представляет из себя значительно упрощенную схему восприятия информации мозгом. Целью этого практического задания будет реализация собственной модели перцептрона. Давайте разберем схему работы этого алгоритма в деталях.

* Мы работаем с тренировочной выборкой $S = \{(x_i, y_i)| i \in \{1,...,m\} \}$
* Инициализируем веса $\omega^{(0)} \leftarrow 0$ нулевым вектором.
* Инициализирует bias параметр $b = 0$.
* В начальный момент времени номер шага $t=0$.
* Задаем learning rate $\eta > 0$.
* Пока значение $t < t_{\max}$
    * случайно выбираем объект из тренировочной выборки $(x_i, y_i) \in S$.
    * если выполняется условие $y_i (\langle \omega^{(t)}, x_i\rangle + b) \leq 0$ тогда
        * $b^{(t+1)} \leftarrow b^{(t)} + \eta \times y_i$.
        * $\omega^{(t+1)} \leftarrow \omega^{(t)} + \eta \times y_i \times x_i$.
    * далее, обновляем $t \leftarrow t+1$.

Таким образом, финальное значение ветора весов $\omega$ и bias параметра $b$ позволяют классифицировать новый объект $x$. Если $(\langle \omega, x \rangle + b) \geq 0$, то мы относим объект к классу $+1$, в противном случае мы относим объект к классу $-1$.

Для начала загрузим датасет для задачи классификации цветков Ириса с помощь функции `load_iris` из `sklearn.datasets`. Давайте подготовим данные для задачи бинарной классификации. Для этого выберем первые 100 элементов из данного набора данных. Так же преобразуем класс $0$ в класс $-1$.

In [1]:
import numpy as np
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)
X, y = X[:100], y[:100]
num_features = X.shape[1]
y = np.array([1 if y_i == 1 else -1 for y_i in y])

Реализуйте алгоритм перцептрона приведенный выше. Для выборки случайного объекта из тренировочного датасета по индексу используйте функцию `randint` из модуля `random` с параметрами 0 и n, где n - это размер тренировочно выборки. Перед запуском итераций алгоритма установите `random.seed(42)`. Вы можете реализовать перцептрон в качестве класса с интерфейсом, похожим на интерфейсы моделей из `scikit-learn`. Для этого достаточно реализовать функцию `fit` и `predict` для решения этого практического задания. Однако, ваша реализация может отличаться. Необходимое требование - это использование генератора случайных чисел, описанного выше.

### *РЕШЕНИЕ*

In [120]:
X[:1]

array([[5.1, 3.5, 1.4, 0.2]])

In [126]:
import random
random.seed(42)


class Perceptron:
    def __init__(self, num_features, lr, t_max):
        self.w = np.zeros(num_features)
        self.lr = lr
        self.t_max = t_max
        self.b = 0
    
    def fit(self, X_train, y_train):
        t = 0
        while t < self.t_max:
            x = random.randint(0, X_train.shape[0] - 1)
            if (y_train[x] * np.sum(X_train[x] * self.w) + self.b) <= 0:
                self.b += self.lr * y_train[x]
                print(self.b)
                self.w += self.lr * y_train[x] * X_train[x]
                print(self.w)
            else:
                t += 1
        print(self.w, self.b)

    def predict(self, X_test):
        pred = []
        for ind, x in enumerate(X_test):
            if (np.sum(x * self.w) + self.b) >= 0:
                pred.append(1)
            else:
                pred.append(-1)
        return pred

Следующим шагом является проверка нашей модели. Случайно разделите выборку на тренировочный и тестовый датасет, используя функцию `tran_test_split` с параметрами `test_size=0.25` и `random_state=10`. Запустите обучение модели с параметрами $\eta=0.1$ и $t_{\max}=40$. Оцените качество на тестовой выборке и запишите результат в переменную `score` с точность до двух знаков после запятой, используя метрику `accuracy`. Это значение и будет являться ответом на это практическое задание.

### *РЕШЕНИЕ*

In [127]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=10)
model = Perceptron(num_features, 0.1, 40)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
score = round(accuracy_score(y_test, y_pred), 2)

-0.1
[-0.53 -0.37 -0.15 -0.02]
0.0
[ 0.04 -0.08  0.27  0.11]
-0.1
[-0.5  -0.47  0.1   0.07]
0.0
[ 0.   -0.24  0.43  0.17]
-0.1
[-0.48 -0.58  0.24  0.15]
0.0
[ 0.15 -0.35  0.68  0.28]
-0.1
[-0.36 -0.68  0.51  0.23]
0.0
[ 0.21 -0.4   0.96  0.36]
-0.1
[-0.33 -0.74  0.81  0.32]
0.0
[ 0.18 -0.49  1.11  0.43]
-0.1
[-0.36 -0.83  0.96  0.39]
0.0
[ 0.3  -0.53  1.4   0.53]
-0.1
[-0.2  -0.89  1.26  0.51]
[-0.2  -0.89  1.26  0.51] -0.1


# Строка с ответами

In [128]:
print(f"score {score:.2f}")

score 1.00
